version: '4.2'
services:
  mysql-master:
    image: mysql:latest
    container_name: mysql-master
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: replication_db
      MYSQL_USER: replication_user
      MYSQL_PASSWORD: replication_password
    volumes:
      - master-db-data:/var/lib/mysql
    command: ["mysqld", "--server-id=1", "--log-bin=mysql-bin", "--binlog-do-db=replication_db"]

  mysql-slave:
    image: mysql:latest
    container_name: mysql-slave
    ports:
      - "3307:3306"
    depends_on:
      - mysql-master
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: replication_db
      MYSQL_USER: replication_user
      MYSQL_PASSWORD: replication_password
    volumes:
      - slave-db-data:/var/lib/mysql
    command: ["mysqld", "--server-id=2", "--relay-log=mysql-relay-bin", "--log-bin=mysql-bin"]

volumes:
  master-db-data:
    driver: local
  slave-db-data:
    driver: local
